### ISSUE TITLE
How to use the transform to kitti data

### ISSUE THREAD

**Issue by DominikFle** [abhi1kumar/SeaBird#2]
Hey, 
first thank you for the great work. I also want to predict frame by frame and then merge back into npy windows.
Is there any chance you could provide the script that runs the `get_kitti_style_ground_truth` function.

https://github.com/abhi1kumar/SeaBird/blob/86a04e26dd92972b9a13fef52ed0318cf4c4a244/PanopticBEV/panoptic_bev/helpers/kitti_360_util.py#L132
Thank you

**Comment by abhi1kumar** [comment]
Hi @DominikFle 

> I also want to predict frame by frame and then merge back into npy windows.

Thank you for your interest in SeaBird. We already released the KITTI-360 labels in the KITTI format, which we had used for our experiments [here in the KITTI-360 Data section](https://github.com/abhi1kumar/SeaBird/tree/main/PanopticBEV#setup). Will that work?

**Comment by DominikFle** [comment]
Thanks for the quick reply,
the labels are nice as a start. Do you have a mapping from the raw data indices given in kitti360 and your label indices ?
![grafik](https://github.com/abhi1kumar/SeaBird/assets/75590579/55913c97-8b55-4af6-94a5-e00858f38174)

Still i would be interested in the script to create the data, and also then merge the predictions back into the windows.
PS. I of course already starred such a great repo :wink:

**Comment by abhi1kumar** [comment]
> Do you have a mapping from the raw data indices given in kitti360 and your label indices ?
![grafik](https://github.com/abhi1kumar/SeaBird/assets/75590579/55913c97-8b55-4af6-94a5-e00858f38174)

Yes. There are two ways to get to the original mapping:

1. **Use `real_path` of soft links**: The following function 
https://github.com/abhi1kumar/SeaBird/blob/86a04e26dd92972b9a13fef52ed0318cf4c4a244/PanopticBEV/panoptic_bev/helpers/kitti_360_util.py#L262

uses the real path of images to convert them to KITTI windows [here](https://github.com/abhi1kumar/SeaBird/blob/86a04e26dd92972b9a13fef52ed0318cf4c4a244/PanopticBEV/panoptic_bev/helpers/kitti_360_util.py#L392).

2. **Use ImageSets original `org` files**:  We kept the original path of the mapped files in the [ImageSets](https://github.com/abhi1kumar/SeaBird/tree/86a04e26dd92972b9a13fef52ed0318cf4c4a244/PanopticBEV/data/kitti_360/ImageSets) folder. You could count the number of lines in the org and vanilla files to get the correct org files.

Mapped | Original File |  Images
------ | ---- | -----
`train_det.txt` | `org_train_det_clean.txt` | 48648
`val_det.txt`   |  `org_val_det_clean.txt` | 12408
`val_det_samp.txt` | `org_val_det_samp.txt` | 1248
`trainval_det.txt` | `org_trainval_det_clean.txt` | 61056
`test_det.txt`  | `org_test_det_samp.txt`  | 910

As an example, `org_train_det_clean.txt` stores the original paths of `train_det.txt`. So, `2013_05_28_drive_0004_sync;0000009808.png` is the original name of the file `054295.png`

> Still i would be interested in the script to create the data

I will look for it. I did the conversion in early 2023 and the script should be in my old HDD. 

> also then merge the predictions back into the windows.

`convert_kitti_image_text_to_kitti_360_window_npy` [function](https://github.com/abhi1kumar/SeaBird/blob/86a04e26dd92972b9a13fef52ed0318cf4c4a244/PanopticBEV/panoptic_bev/helpers/kitti_360_util.py#L262) merges the predictions back into windows.

> I of course already starred such a great repo :wink: 

Thank you for supporting us, I am honored :smile:

**Comment by DominikFle** [comment]
Thank you again for the immediate and concise answer.
Focussing on the 2nd approach for mapping your labels to the orignal indices. Do I understand correct that
- you divide the dataset into train and val for your own eval and than into train_val and test for submission?
- Each line in the mapped txts (e.g `train_det.txt`) corresponds to the same line in the orignal file txts (e.g `org_train_det_clean.txt`) ?

Why is the first line `2013_05_28_drive_0004_sync;0000009808.png` than equivalent to `054295.png` (the number of lines in the `org_train_det`) I would have though it would be `000000.png` as it is the first line in the `train_det.txt`

> I will look for it. I did the conversion in early 2023 and the script should be in my old HDD.

That would be gold for me :)
Thank you

**Comment by abhi1kumar** [comment]
Welcome. 

> - you divide the dataset into train and val for your own eval and than into train_val and test for submission?

KITTI-360 provides train/val/test [windows](https://github.com/abhi1kumar/SeaBird/tree/main/PanopticBEV/data/kitti_360/ImageSets/windows). We subsample train and val windows for val split and use all train+val and test images with calibration for the leaderboard submission. Please see [Sec A2, Data Splits](https://arxiv.org/pdf/2403.20318.pdf) of the supplementary for more details.

> - Each line in the mapped txts (e.g `train_det.txt`) corresponds to the same line in the orignal file txts (e.g `org_train_det_clean.txt`) ?

You are correct. The **first line** of `org_train_det_clean.txt` corresponds to the **first line** of `train_det.txt`. 

> Why is the first line 2013_05_28_drive_0004_sync;0000009808.png than equivalent to 054295.png (the number of lines in the org_train_det) I would have though it would be 000000.png as it is the first line in the train_det.txt

Since there is subsampling, the order gets changed and that is why, the first line of `org_train_det_clean.txt` does **NOT** correspond to `00000.txt`

**Comment by DominikFle** [comment]
Thanks for clarifying. Unfortunately I still dont get the mapping from original to your indexing method. But you helped me a lot!
One final question your labels are then only within the camera frustum in from of the ego vehicle right ?

**Comment by abhi1kumar** [comment]
> One final question your labels are then only within the camera frustum in front of the ego vehicle right ?

Yes, the processed labels in KITTI format are within the camera frustum.

**Comment by HarisAmir** [comment]
> I will look for it. I did the conversion in early 2023 and the script should be in my old HDD.

Any update on this end? I was also interested in the label conversion script from KITTI 360 to KITTI format.
