### ISSUE TITLE
dice loss

### ISSUE THREAD

**Issue by huzkun** [abhi1kumar/SeaBird#4]
In which folder is dice loss located?

**Comment by abhi1kumar** [comment]
Hi @huzkun 
Thank you for your interest in SeaBird. The dice loss is implemented here in these two models:

- **PanopticBEV (KITTI-360 Single Camera Models)**: 
https://github.com/abhi1kumar/SeaBird/blob/0fd45183128f7d8615263e330484e2545004607c/PanopticBEV/panoptic_bev/algos/semantic_seg.py#L166-L176

- **HoP (nuScenes Multi-Camera Models)**: 
https://github.com/abhi1kumar/SeaBird/blob/0fd45183128f7d8615263e330484e2545004607c/HoP/mmdet3d_plugin/models/dense_heads/loss_utils.py#L22-L38

PS: It would be great if you could support our repo by starring it.

**Comment by huzkun** [comment]
Thanks for your answer, seabird is a great job.
