### ISSUE TITLE
Conversion script for labels from KITTI 360 to KITTI format

### ISSUE THREAD

**Issue by HarisAmir** [abhi1kumar/SeaBird#6]
Hello 👋

Although they are uploaded already, I was interested in how did you convert the labels from **KITTI-360** to **KITTI** format?

Could you please share that code if possible.

Thanks in advance

**Comment by abhi1kumar** [comment]
Hi @HarisAmir 

Thank you for your interest in SeaBird. You could find all the helper scripts such as [get_kitti_style_ground_truth()](https://github.com/abhi1kumar/SeaBird/blob/main/PanopticBEV/panoptic_bev/helpers/kitti_360_util.py#L132-L259) for conversion inside [kitti360_util.py](https://github.com/abhi1kumar/SeaBird/blob/main/PanopticBEV/panoptic_bev/helpers/kitti_360_util.py) file. Unfortunately, the wrapper script of `get_kitti_style_ground_truth()` was on my old HDD, and I have not searched for it. 

However, the converted KITTI-360 labels in KITTI format are already released, and you could use it to train KITTI style 3D detectors / BEV segmentors.

**Comment by abhi1kumar** [comment]
Hi @HarisAmir 

I found a version of wrapper script [kitti_360_converter.py](https://github.com/abhi1kumar/SeaBird/blob/main/PanopticBEV/data/kitti_360/kitti_360_converter.py), which I added to the repo now. You could run the script inside the PanopticBEV conda environment to convert KITTI-360 labels to KITTI format as follows:

```
python data/kitti_360/kitti_360_converter.py
```

Please check. Let me know if you need more help.

**Comment by abhi1kumar** [comment]
Closing this issue but feel free to open it.
