### ISSUE TITLE
Results on KITTI360 val set

### ISSUE THREAD

**Issue by KuanchihHuang** [abhi1kumar/SeaBird#7]
Thank you for open-sourcing the awesome work! 

I want to reproduce the metric on KITTI-360 Val with the released pre-trained weight.

Here is the results below, I found that the number is slightly different. Is this normal?

Released table in the repo:
```bash
Metrics | Lrg(50) | Car(50) | Mean(50) | Lrg(25) | Car(25) | Mean(25)
AP | 13.22 | 42.46 | 27.84 | 37.15 | 52.53 | 44.84
```

What I have with the released checkpoint:

```bash
19:09:57 Pred_folder = ./output/pbev_seabird_kitti360_val/result_19_val_det_samp/data_kitti_360_format
GT_folder   = data/kitti_360/ImageSets/windows/train_og
Evaluating 61 pairs of windows...

Windows Processed: 61

19:10:09 ----------------------bld_AP car_AP  mAP  bld_R car_R   AR
19:10:09 window iou_thresh: 0.50 13.26 42.82 28.04 26.08 61.37 43.72
19:10:20 window iou_thresh: 0.25 37.08 52.71 44.90 48.94 67.38 58.16
```

I have the several questions:

1. Is the table in the repo for the val_det_samp split?
2. Is  Lrg(50) the same as bld_AP for iou_thresh: 0.50?

Thank you!

**Comment by abhi1kumar** [comment]
Hi @KuanchihHuang 

Thank you for your interest in SeaBird.

> 1. Is the table in the repo for the val_det_samp split?

Yes, it is for val_det_samp split. You could check out the Data splits section in the Supplementary for details.

> 2. Is Lrg(50) the same as bld_AP for iou_thresh: 0.50?

Yes. The large objects in SeaBird paper refers to a category which has mean shape bigger than Car. KITTI-360 has only two categories: Cars and Buildings. Therefore, Building is the only large category for KITTI-360.

PS: It would be great if you could support our repo by starring it.

**Comment by KuanchihHuang** [comment]
Thanks for your reply. Sure, I have already stared it!

One more question, should my inference results with the released checkpoint match yours? My results aren’t aligning with those in the table (though super close), so I'm concerned I may have missed something.

**Comment by abhi1kumar** [comment]
It is already matching. 

Table AP (%) | Reproduced AP (%)
-- | --
13.22 | 13.26
42.46 | 42.82
27.84 | 28.04
37.15 | 37.08
52.53 | 52.71
44.84 | 44.90

The fluctuation in the second digit of decimal is OK.

**Comment by KuanchihHuang** [comment]
Yes, it looks like we're all set here. Thanks for confirming!
